import { Module } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';
import { ScheduleModule } from '@nestjs/schedule';
import {
  DatabaseModule,
  KafkaModule,
  LoggerModule,
  TranslateModule,
  ValidationModule,
} from '@zro/common';
import { JdpiPixModule } from '@zro/jdpi';
import {
  PixKeyEventKafkaEmitterInit,
  SyncPendingPixKeyCronService,
  SyncClaimPendingExpiredPixKeyCronService,
  SyncOwnershipPendingExpiredPixKeyCronService,
  DeletingPixKeyNestObserver,
  PixKeyModel,
  PixKeyVerificationModel,
  ApproveOwnershipClaimStartProcessMicroserviceController,
  VerifyCodePixKeyMicroserviceController,
  SendCodePixKeyMicroserviceController,
  ConfirmedPixKeyNestObserver,
  OwnershipOpenedPixKeyNestObserver,
  CancelStartClaimProcessByIdPixKeyMicroserviceController,
  CancelStartPortabilityProcessByIdPixKeyMicroserviceController,
  CreatePixKeyMicroserviceController,
  DeleteByIdPixKeyMicroserviceController,
  DismissByIdPixKeyMicroserviceController,
  GetAllPixKeyMicroserviceController,
  GetAllPixKeyByUserMicroserviceController,
  GetByIdPixKeyMicroserviceController,
  PortabilityOpenedPixKeyNestObserver,
  ApprovePortabilityClaimStartProcessMicroserviceController,
  ApprovePortabilityClaimProcessMicroserviceController,
  CancelPortabilityRequestClaimProcessMicroserviceController,
  PortabilityRequestCancelPixKeyNestObserver,
  PortabilityRequestConfirmPixKeyNestObserver,
  HistoryPixKeyNestObserver,
  PixKeyHistoryModel,
  GetHistoryPixKeyMicroserviceController,
  CancelCodePixKeyMicroserviceController,
  ClaimClosingPixKeyNestObserver,
  ClaimDeniedPixKeyNestObserver,
  GetByKeyPixKeyMicroserviceController,
  CancelOwnershipClaimProcessMicroserviceController,
  CancelPortabilityClaimProcessMicroserviceController,
  CompleteClosingClaimProcessMicroserviceController,
  CompleteOwnershipClaimProcessMicroserviceController,
  CompletePortabilityClaimProcessMicroserviceController,
  ConfirmOwnershipClaimProcessMicroserviceController,
  ConfirmPortabilityClaimProcessMicroserviceController,
  ReadyOwnershipClaimProcessMicroserviceController,
  ReadyPortabilityClaimProcessMicroserviceController,
  WaitOwnershipClaimProcessMicroserviceController,
  WaitPortabilityClaimProcessMicroserviceController,
  ClaimPendingExpiredPixKeyNestObserver,
  PendingExpiredPixKeyNestObserver,
  GetPixKeyByKeyAndUserMicroserviceController,
  OwnershipPendingExpiredPixKeyNestObserver,
  CancelingOwnershipClaimProcessMicroserviceController,
  CancelingPortabilityClaimProcessMicroserviceController,
  OwnershipCancelingPixKeyNestObserver,
  PortabilityCancelingPixKeyNestObserver,
  ErrorDecodedPixKeyNestObserver,
  SyncPortabilityRequestPendingPixKeyCronService,
  SyncPortabilityPendingExpiredPixKeyCronService,
  PortabilityPendingExpiredPixKeyNestObserver,
} from '@zro/pix-keys/infrastructure';
import {
  SendEmailServiceKafka,
  SendSmsServiceKafka,
} from '@zro/notifications/infrastructure';
import { GetOnboardingByUserAndStatusIsFinishedServiceKafka } from '@zro/users/infrastructure';

@Module({
  imports: [
    ScheduleModule.forRoot(),
    ConfigModule,
    LoggerModule,
    ValidationModule,
    KafkaModule.forFeature([
      SendEmailServiceKafka,
      SendSmsServiceKafka,
      GetOnboardingByUserAndStatusIsFinishedServiceKafka,
    ]),
    DatabaseModule.forFeature([
      PixKeyModel,
      PixKeyVerificationModel,
      PixKeyHistoryModel,
    ]),
    JdpiPixModule,
    TranslateModule,
  ],
  controllers: [
    DeletingPixKeyNestObserver,
    ConfirmedPixKeyNestObserver,
    OwnershipOpenedPixKeyNestObserver,
    PortabilityOpenedPixKeyNestObserver,
    SendCodePixKeyMicroserviceController,
    VerifyCodePixKeyMicroserviceController,
    ApproveOwnershipClaimStartProcessMicroserviceController,
    ApprovePortabilityClaimStartProcessMicroserviceController,
    CancelStartClaimProcessByIdPixKeyMicroserviceController,
    CancelStartPortabilityProcessByIdPixKeyMicroserviceController,
    ApprovePortabilityClaimProcessMicroserviceController,
    CancelPortabilityRequestClaimProcessMicroserviceController,
    CreatePixKeyMicroserviceController,
    DeleteByIdPixKeyMicroserviceController,
    DismissByIdPixKeyMicroserviceController,
    GetAllPixKeyMicroserviceController,
    GetAllPixKeyByUserMicroserviceController,
    GetByIdPixKeyMicroserviceController,
    PortabilityRequestConfirmPixKeyNestObserver,
    PortabilityRequestCancelPixKeyNestObserver,
    HistoryPixKeyNestObserver,
    GetHistoryPixKeyMicroserviceController,
    CancelCodePixKeyMicroserviceController,
    ClaimClosingPixKeyNestObserver,
    ClaimDeniedPixKeyNestObserver,
    GetByKeyPixKeyMicroserviceController,
    CancelOwnershipClaimProcessMicroserviceController,
    CancelPortabilityClaimProcessMicroserviceController,
    CompleteClosingClaimProcessMicroserviceController,
    CompleteOwnershipClaimProcessMicroserviceController,
    CompletePortabilityClaimProcessMicroserviceController,
    ConfirmOwnershipClaimProcessMicroserviceController,
    ConfirmPortabilityClaimProcessMicroserviceController,
    ReadyOwnershipClaimProcessMicroserviceController,
    ReadyPortabilityClaimProcessMicroserviceController,
    WaitOwnershipClaimProcessMicroserviceController,
    WaitPortabilityClaimProcessMicroserviceController,
    ClaimPendingExpiredPixKeyNestObserver,
    PendingExpiredPixKeyNestObserver,
    GetPixKeyByKeyAndUserMicroserviceController,
    OwnershipPendingExpiredPixKeyNestObserver,
    CancelingOwnershipClaimProcessMicroserviceController,
    CancelingPortabilityClaimProcessMicroserviceController,
    OwnershipCancelingPixKeyNestObserver,
    PortabilityCancelingPixKeyNestObserver,
    ErrorDecodedPixKeyNestObserver,
    PortabilityPendingExpiredPixKeyNestObserver,
  ],
  providers: [
    PixKeyEventKafkaEmitterInit,
    SyncPendingPixKeyCronService,
    SyncClaimPendingExpiredPixKeyCronService,
    SyncOwnershipPendingExpiredPixKeyCronService,
    SyncPortabilityRequestPendingPixKeyCronService,
    SyncPortabilityPendingExpiredPixKeyCronService,
  ],
})
export class PixKeyModule {}
