const git = require('git-last-commit');

type GitUser = { name: string; email: string };

type GitCommit = {
  shortHash: string;
  hash: string;
  subject: string;
  sanitizedSubject: string;
  body: string;
  authoredOn: Date;
  committedOn: Date;
  author: GitUser;
  committer: GitUser;
  notes: string;
  branch: string;
  tags: string[];
};

async function getLastCommit(): Promise<GitCommit> {
  return new Promise((resolve) => {
    // read commit object properties
    git.getLastCommit(function (err, commit) {
      const result = commit;
      result.authoredOn = new Date(parseInt(commit.authoredOn) * 1000);
      result.committedOn = new Date(parseInt(commit.committedOn) * 1000);

      resolve(result);
    });
  });
}

export default async () => {
  const commit = await getLastCommit();

  return {
    globals: {
      _BUILD_INFO_: {
        package: {
          version: JSON.stringify(require('./package.json').version),
        },
        git: {
          version: JSON.stringify(commit.shortHash),
          commitHash: JSON.stringify(commit.hash),
          branch: JSON.stringify(commit.branch),
          lastCommitDatetime: JSON.stringify(commit.committedOn),
        },
      },
    },
    testPathIgnorePatterns: [],
    setupFiles: ['<rootDir>/config/test/setup_files.ts'],
    testSequencer: '<rootDir>/config/test/sequencer.js',
    moduleFileExtensions: ['js', 'json', 'ts'],
    rootDir: '.',
    testRegex: '.*\\.spec\\.(ts|js)$',
    transform: {
      '^.+\\.(t|j)s$': ['ts-jest', { compiler: 'ttypescript' }],
    },
    collectCoverageFrom: ['**/*.(t|j)s'],
    coverageDirectory: './coverage',
    testEnvironment: 'node',
    roots: ['<rootDir>/apps/', '<rootDir>/libs/'],
    moduleNameMapper: {
      '@zro/apilayer/(.*)': '<rootDir>/libs/apilayer/src/$1',
      '@zro/apilayer': '<rootDir>/libs/apilayer/src',
      '@zro/common/(.*)': '<rootDir>/libs/common/src/$1',
      '@zro/common': '<rootDir>/libs/common/src',
      '@zro/dock/(.*)': '<rootDir>/libs/dock/src/$1',
      '@zro/dock': '<rootDir>/libs/dock/src',
      '@zro/matraca/(.*)': '<rootDir>/libs/matraca/src/$1',
      '@zro/matraca': '<rootDir>/libs/matraca/src',
      '@zro/tradair/(.*)': '<rootDir>/libs/tradair/src/$1',
      '@zro/tradair': '<rootDir>/libs/tradair/src',
      '@zro/zenvia/(.*)': '<rootDir>/libs/zenvia/src/$1',
      '@zro/zenvia': '<rootDir>/libs/zenvia/src',
      '@zro/b2c2/(.*)': '<rootDir>/libs/b2c2/src/$1',
      '@zro/b2c2': '<rootDir>/libs/b2c2/src',
      '@zro/binance/(.*)': '<rootDir>/libs/binance/src/$1',
      '@zro/binance': '<rootDir>/libs/binance/src',
      '@zro/mercado-bitcoin/(.*)': '<rootDir>/libs/mercado-bitcoin/src/$1',
      '@zro/mercado-bitcoin': '<rootDir>/libs/mercado-bitcoin/src',
      '@zro/bulksms/(.*)': '<rootDir>/libs/bulksms/src/$1',
      '@zro/bulksms': '<rootDir>/libs/bulksms/src',
      '@zro/topazio/(.*)': '<rootDir>/libs/topazio/src/$1',
      '@zro/topazio': '<rootDir>/libs/topazio/src',
      '@zro/jdpi/(.*)': '<rootDir>/libs/jdpi/src/$1',
      '@zro/jdpi': '<rootDir>/libs/jdpi/src',
      '@zro/jira/(.*)': '<rootDir>/libs/jira/src/$1',
      '@zro/jira': '<rootDir>/libs/jira/src',
      '@zro/gateway-webhook/(.*)': '<rootDir>/libs/gateway-webhook/src/$1',
      '@zro/gateway-webhook': '<rootDir>/libs/gateway-webhook/src',
      '@zro/file-storage/(.*)': '<rootDir>/libs/file-storage/src/$1',
      '@zro/file-storage': '<rootDir>/libs/file-storage/src',
      '@zro/s3-storage/(.*)': '<rootDir>/libs/s3-storage/src/$1',
      '@zro/s3-storage': '<rootDir>/libs/s3-storage/src',
      '@zro/fcm/(.*)': '<rootDir>/libs/fcm/src/$1',
      '@zro/fcm': '<rootDir>/libs/fcm/src',
      '@zro/e-guardian/(.*)': '<rootDir>/libs/e-guardian/src/$1',
      '@zro/e-guardian': '<rootDir>/libs/e-guardian/src',
      '@zro/asaas/(.*)': '<rootDir>/libs/asaas/src/$1',
      '@zro/asaas': '<rootDir>/libs/asaas/src',
      '@zro/genial/(.*)': '<rootDir>/libs/genial/src/$1',
      '@zro/genial': '<rootDir>/libs/genial/src',
      '@zro/zrobank/(.*)': '<rootDir>/libs/zrobank/src/$1',
      '@zro/zrobank': '<rootDir>/libs/zrobank/src',
      '@zro/api-caas/(.*)': '<rootDir>/apps/api-caas/src/$1',
      '@zro/api-caas': '<rootDir>/apps/api-caas/src',
      '@zro/api-admin/(.*)': '<rootDir>/apps/api-admin/src/$1',
      '@zro/api-admin': '<rootDir>/apps/api-admin/src',
      '@zro/api-topazio/(.*)': '<rootDir>/apps/api-topazio/src/$1',
      '@zro/api-topazio': '<rootDir>/apps/api-topazio/src',
      '@zro/api-jdpi/(.*)': '<rootDir>/apps/api-jdpi/src/$1',
      '@zro/api-jdpi': '<rootDir>/apps/api-jdpi/src',
      '@zro/api-jira/(.*)': '<rootDir>/apps/api-jira/src/$1',
      '@zro/api-jira': '<rootDir>/apps/api-jira/src',
      '@zro/api-users/(.*)': '<rootDir>/apps/api-users/src/$1',
      '@zro/api-users': '<rootDir>/apps/api-users/src',
      '@zro/api-grafana/(.*)': '<rootDir>/apps/api-grafana/src/$1',
      '@zro/api-grafana': '<rootDir>/apps/api-grafana/src',
      '@zro/api-asaas/(.*)': '<rootDir>/apps/api-asaas/src/$1',
      '@zro/api-asaas': '<rootDir>/apps/api-asaas/src',
      '@zro/api-genial/(.*)': '<rootDir>/apps/api-genial/src/$1',
      '@zro/api-genial': '<rootDir>/apps/api-genial/src',
      '@zro/api-pix-zro-pay/(.*)': '<rootDir>/apps/api-pix-zro-pay/src/$1',
      '@zro/api-pix-zro-pay': '<rootDir>/apps/api-pix-zro-pay/src',
      '@zro/api-open-banking/(.*)': '<rootDir>/apps/api-open-banking/src/$1',
      '@zro/api-open-banking': '<rootDir>/apps/api-open-banking/src',
      '@zro/infra-retry/(.*)': '<rootDir>/apps/infra-retry/src/$1',
      '@zro/infra-retry': '<rootDir>/apps/infra-retry/src',
      '@zro/banking/(.*)': '<rootDir>/apps/banking/src/$1',
      '@zro/banking': '<rootDir>/apps/banking/src',
      '@zro/compliance/(.*)': '<rootDir>/apps/compliance/src/$1',
      '@zro/compliance': '<rootDir>/apps/compliance/src',
      '@zro/notifications/(.*)': '<rootDir>/apps/notifications/src/$1',
      '@zro/notifications': '<rootDir>/apps/notifications/src',
      '@zro/operations/(.*)': '<rootDir>/apps/operations/src/$1',
      '@zro/operations': '<rootDir>/apps/operations/src',
      '@zro/otc-bot/(.*)': '<rootDir>/apps/otc-bot/src/$1',
      '@zro/otc-bot': '<rootDir>/apps/otc-bot/src',
      '@zro/otc/(.*)': '<rootDir>/apps/otc/src/$1',
      '@zro/otc': '<rootDir>/apps/otc/src',
      '@zro/pix-keys/(.*)': '<rootDir>/apps/pix-keys/src/$1',
      '@zro/pix-keys': '<rootDir>/apps/pix-keys/src',
      '@zro/pix-payments/(.*)': '<rootDir>/apps/pix-payments/src/$1',
      '@zro/pix-payments': '<rootDir>/apps/pix-payments/src',
      '@zro/quotations/(.*)': '<rootDir>/apps/quotations/src/$1',
      '@zro/quotations': '<rootDir>/apps/quotations/src',
      '@zro/reports/(.*)': '<rootDir>/apps/reports/src/$1',
      '@zro/reports': '<rootDir>/apps/reports/src',
      '@zro/users/(.*)': '<rootDir>/apps/users/src/$1',
      '@zro/users': '<rootDir>/apps/users/src',
      '@zro/webhooks/(.*)': '<rootDir>/apps/webhooks/src/$1',
      '@zro/webhooks': '<rootDir>/apps/webhooks/src',
      '@zro/admin/(.*)': '<rootDir>/apps/admin/src/$1',
      '@zro/admin': '<rootDir>/apps/admin/src',
      '@zro/storage/(.*)': '<rootDir>/apps/storage/src/$1',
      '@zro/storage': '<rootDir>/apps/storage/src',
      '@zro/signup/(.*)': '<rootDir>/apps/signup/src/$1',
      '@zro/signup': '<rootDir>/apps/signup/src',
      '@zro/picpay/(.*)': '<rootDir>/apps/picpay/src/$1',
      '@zro/picpay': '<rootDir>/apps/picpay/src',
      '@zro/nupay/(.*)': '<rootDir>/apps/nupay/src/$1',
      '@zro/nupay': '<rootDir>/apps/nupay/src',
      '@zro/cielo/(.*)': '<rootDir>/apps/cielo/src/$1',
      '@zro/cielo': '<rootDir>/apps/cielo/src',
      '@zro/utils/(.*)': '<rootDir>/apps/utils/src/$1',
      '@zro/utils': '<rootDir>/apps/utils/src',
      '@zro/payments-gateway/(.*)': '<rootDir>/apps/payments-gateway/src/$1',
      '@zro/payments-gateway': '<rootDir>/apps/payments-gateway/src',
      '@zro/pix-zro-pay/(.*)': '<rootDir>/apps/pix-zro-pay/src/$1',
      '@zro/pix-zro-pay': '<rootDir>/apps/pix-zro-pay/src',
      '@zro/test/apilayer/(.*)': '<rootDir>/libs/apilayer/test/$1',
      '@zro/test/apilayer': '<rootDir>/libs/apilayer/test',
      '@zro/test/api-caas/(.*)': '<rootDir>/apps/api-caas/test/$1',
      '@zro/test/api-caas': '<rootDir>/apps/api-caas/test',
      '@zro/test/api-topazio/(.*)': '<rootDir>/apps/api-topazio/test/$1',
      '@zro/test/api-topazio': '<rootDir>/apps/api-topazio/test',
      '@zro/test/api-jdpi/(.*)': '<rootDir>/apps/api-jdpi/test/$1',
      '@zro/test/api-jdpi': '<rootDir>/apps/api-jdpi/test',
      '@zro/test/api-jira/(.*)': '<rootDir>/apps/api-jira/test/$1',
      '@zro/test/api-jira': '<rootDir>/apps/api-jira/test',
      '@zro/test/api-users/(.*)': '<rootDir>/apps/api-users/test/$1',
      '@zro/test/api-users': '<rootDir>/apps/api-users/test',
      '@zro/test/api-grafana/(.*)': '<rootDir>/apps/api-grafana/test/$1',
      '@zro/test/api-grafana': '<rootDir>/apps/api-grafana/test',
      '@zro/test/api-paas/(.*)': '<rootDir>/apps/api-paas/test/$1',
      '@zro/test/api-paas': '<rootDir>/apps/api-paas/test',
      '@zro/test/api-admin/(.*)': '<rootDir>/apps/api-admin/test/$1',
      '@zro/test/api-admin': '<rootDir>/apps/api-admin/test',
      '@zro/test/api-asaas/(.*)': '<rootDir>/apps/api-asaas/test/$1',
      '@zro/test/api-asaas': '<rootDir>/apps/api-asaas/test',
      '@zro/test/api-genial/(.*)': '<rootDir>/apps/api-genial/test/$1',
      '@zro/test/api-genial': '<rootDir>/apps/api-genial/test',
      '@zro/test/api-pix-zro-pay/(.*)':
        '<rootDir>/apps/api-pix-zro-pay/test/$1',
      '@zro/test/api-pix-zro-pay': '<rootDir>/apps/api-pix-zro-pay/test',
      '@zro/test/api-open-banking/(.*)':
        '<rootDir>/apps/api-open-banking/test/$1',
      '@zro/test/api-open-banking': '<rootDir>/apps/api-open-banking/test',
      '@zro/test/infra-retry/(.*)': '<rootDir>/apps/infra-retry/test/$1',
      '@zro/test/infra-retry': '<rootDir>/apps/infra-retry/test',
      '@zro/test/banking/(.*)': '<rootDir>/apps/banking/test/$1',
      '@zro/test/banking': '<rootDir>/apps/banking/test',
      '@zro/test/compliance/(.*)': '<rootDir>/apps/compliance/test/$1',
      '@zro/test/compliance': '<rootDir>/apps/compliance/test',
      '@zro/test/notifications/(.*)': '<rootDir>/apps/notifications/test/$1',
      '@zro/test/notifications': '<rootDir>/apps/notifications/test',
      '@zro/test/operations/(.*)': '<rootDir>/apps/operations/test/$1',
      '@zro/test/operations': '<rootDir>/apps/operations/test',
      '@zro/test/otc-bot/(.*)': '<rootDir>/apps/otc-bot/test/$1',
      '@zro/test/otc-bot': '<rootDir>/apps/otc-bot/test',
      '@zro/test/otc/(.*)': '<rootDir>/apps/otc/test/$1',
      '@zro/test/otc': '<rootDir>/apps/otc/test',
      '@zro/test/pix-keys/(.*)': '<rootDir>/apps/pix-keys/test/$1',
      '@zro/test/pix-keys': '<rootDir>/apps/pix-keys/test',
      '@zro/test/pix-payments/(.*)': '<rootDir>/apps/pix-payments/test/$1',
      '@zro/test/pix-payments': '<rootDir>/apps/pix-payments/test',
      '@zro/test/picpay/(.*)': '<rootDir>/apps/picpay/test/$1',
      '@zro/test/picpay': '<rootDir>/apps/picpay/test',
      '@zro/test/nupay/(.*)': '<rootDir>/apps/nupay/test/$1',
      '@zro/test/nupay': '<rootDir>/apps/nupay/test',
      '@zro/test/cielo/(.*)': '<rootDir>/apps/cielo/test/$1',
      '@zro/test/cielo': '<rootDir>/apps/cielo/test',
      '@zro/test/quotations/(.*)': '<rootDir>/apps/quotations/test/$1',
      '@zro/test/quotations': '<rootDir>/apps/quotations/test',
      '@zro/test/reports/(.*)': '<rootDir>/apps/reports/test/$1',
      '@zro/test/reports': '<rootDir>/apps/reports/test',
      '@zro/test/users/(.*)': '<rootDir>/apps/users/test/$1',
      '@zro/test/users': '<rootDir>/apps/users/test',
      '@zro/test/webhooks/(.*)': '<rootDir>/apps/webhooks/test/$1',
      '@zro/test/webhooks': '<rootDir>/apps/webhooks/test',
      '@zro/test/admin/(.*)': '<rootDir>/apps/admin/test/$1',
      '@zro/test/admin': '<rootDir>/apps/admin/test',
      '@zro/test/storage/(.*)': '<rootDir>/apps/storage/test/$1',
      '@zro/test/storage': '<rootDir>/apps/storage/test',
      '@zro/test/signup/(.*)': '<rootDir>/apps/signup/test/$1',
      '@zro/test/signup': '<rootDir>/apps/signup/test',
      '@zro/test/matraca/(.*)': '<rootDir>/libs/matraca/test/$1',
      '@zro/test/matraca': '<rootDir>/libs/matraca/test',
      '@zro/test/topazio/(.*)': '<rootDir>/libs/topazio/test/$1',
      '@zro/test/topazio': '<rootDir>/libs/topazio/test',
      '@zro/test/jdpi/(.*)': '<rootDir>/libs/jdpi/test/$1',
      '@zro/test/jdpi': '<rootDir>/libs/jdpi/test',
      '@zro/test/jira/(.*)': '<rootDir>/libs/jira/test/$1',
      '@zro/test/jira': '<rootDir>/libs/jira/test',
      '@zro/test/gateway-webhook/(.*)':
        '<rootDir>/libs/gateway-webhook/test/$1',
      '@zro/test/gateway-webhook': '<rootDir>/libs/gateway-webhook/test',
      '@zro/test/file-storage/(.*)': '<rootDir>/libs/file-storage/test/$1',
      '@zro/test/file-storage': '<rootDir>/libs/file-storage/test',
      '@zro/test/s3-storage/(.*)': '<rootDir>/libs/s3-storage/test/$1',
      '@zro/test/s3-storage': '<rootDir>/libs/s3-storage/test',
      '@zro/test/zenvia/(.*)': '<rootDir>/libs/zenvia/test/$1',
      '@zro/test/zenvia': '<rootDir>/libs/zenvia/test',
      '@zro/test/b2c2/(.*)': '<rootDir>/libs/b2c2/test/$1',
      '@zro/test/b2c2': '<rootDir>/libs/b2c2/test',
      '@zro/test/binance/(.*)': '<rootDir>/libs/binance/test/$1',
      '@zro/test/binance': '<rootDir>/libs/binance/test',
      '@zro/test/mercado-bitcoin/(.*)':
        '<rootDir>/libs/mercado-bitcoin/test/$1',
      '@zro/test/mercado-bitcoin': '<rootDir>/libs/mercado-bitcoin/test',
      '@zro/test/bulksms/(.*)': '<rootDir>/libs/bulksms/test/$1',
      '@zro/test/bulksms': '<rootDir>/libs/bulksms/test',
      '@zro/test/e-guardian/(.*)': '<rootDir>/libs/e-guardian/test/$1',
      '@zro/test/e-guardian': '<rootDir>/libs/e-guardian/test',
      '@zro/test/asaas/(.*)': '<rootDir>/libs/asaas/test/$1',
      '@zro/test/asaas': '<rootDir>/libs/asaas/test',
      '@zro/test/genial/(.*)': '<rootDir>/libs/genial/test/$1',
      '@zro/test/genial': '<rootDir>/libs/genial/test',
      '@zro/test/zrobank/(.*)': '<rootDir>/libs/zrobank/test/$1',
      '@zro/test/zrobank': '<rootDir>/libs/zrobank/test',
      '@zro/test/payments-gateway/(.*)':
        '<rootDir>/apps/payments-gateway/test/$1',
      '@zro/test/payments-gateway': '<rootDir>/apps/payments-gateway/test',
      '@zro/test/pix-zro-pay/(.*)': '<rootDir>/apps/pix-zro-pay/test/$1',
      '@zro/test/pix-zro-pay': '<rootDir>/apps/pix-zro-pay/test',
      '@zro/test/utils/(.*)': '<rootDir>/apps/utils/test/$1',
      '@zro/test/utils': '<rootDir>/apps/utils/test',
      '@zro/assets/otc/(.*)': '<rootDir>/apps/otc/assets/$1',
      '@zro/assets/otc': '<rootDir>/apps/otc/assets',
    },
  };
};
