import { Module } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';
import { KafkaModule, LoggerModule, ValidationModule } from '@zro/common';
import {
  GetAllSystemRestController,
  GetAllSystemServiceKafka,
  GetAllProviderRestController,
  GetAllProviderServiceKafka,
  CreateExchangeContractRestController,
  MountExchangeContractServiceKafka,
  GetAllTaxRestController,
  UpdateExchangeContractServiceKafka,
  UpdateExchangeContractRestController,
  UploadExchangeContractFileRestController,
  GetAllExchangeContractRestController,
  GenerateExchangeContractWorksheetRestController,
  RemoveExchangeContractFileRestController,
  CreateSpreadRestController,
  DeleteSpreadRestController,
  GetAllSpreadRestController,
  GetSpreadByIdRestController,
  CreateSpreadServiceKafka,
  DeleteSpreadServiceKafka,
  GetAllSpreadServiceKafka,
  GetSpreadByIdServiceKafka,
  CreateRemittanceExposureRuleRestController,
  CreateRemittanceOrderRestController,
  UpdateRemittanceExposureRuleRestController,
  GetAllRemittanceExposureRuleRestController,
  GetAllExchangeQuotationRestController,
  GetAllRemittanceOrdersByFilterRestController,
  GetRemittanceOrderByIdRestController,
  GetAllRemittanceRestController,
  ManuallyCloseRemittanceRestController,
  GetRemittanceByIdRestController,
} from '@zro/api-admin/infrastructure';
import {
  GetAllExchangeQuotationServiceKafka,
  UpdateRemittanceExposureRuleServiceKafka,
  GetAllRemittanceExposureRuleServiceKafka,
  CreateRemittanceExposureRuleServiceKafka,
  GetAllRemittanceOrdersByFilterServiceKafka,
  ManuallyCloseRemittanceServiceKafka,
  CreateRemittanceOrderServiceKafka,
  GetAllRemittanceServiceKafka,
  GetRemittanceOrderByIdServiceKafka,
  GetRemittanceByIdServiceKafka,
} from '@zro/otc/infrastructure';

/**
 * Otc endpoint modules.
 */
@Module({
  imports: [
    ConfigModule,
    LoggerModule,
    KafkaModule.forFeature([
      GetAllExchangeQuotationServiceKafka,
      UpdateRemittanceExposureRuleServiceKafka,
      GetAllRemittanceExposureRuleServiceKafka,
      CreateRemittanceExposureRuleServiceKafka,
      GetAllRemittanceOrdersByFilterServiceKafka,
      GetRemittanceOrderByIdServiceKafka,
      GetRemittanceByIdServiceKafka,
      ManuallyCloseRemittanceServiceKafka,
      CreateRemittanceOrderServiceKafka,
      GetAllRemittanceServiceKafka,
    ]),
    ValidationModule,
  ],
  providers: [
    GetAllSystemServiceKafka,
    GetAllProviderServiceKafka,
    MountExchangeContractServiceKafka,
    UpdateExchangeContractServiceKafka,
    CreateSpreadServiceKafka,
    DeleteSpreadServiceKafka,
    GetAllSpreadServiceKafka,
    GetSpreadByIdServiceKafka,
  ],
  controllers: [
    GetAllSystemRestController,
    GetAllProviderRestController,
    CreateExchangeContractRestController,
    GetAllTaxRestController,
    UpdateExchangeContractRestController,
    UploadExchangeContractFileRestController,
    GetAllExchangeContractRestController,
    GenerateExchangeContractWorksheetRestController,
    RemoveExchangeContractFileRestController,
    CreateSpreadRestController,
    DeleteSpreadRestController,
    GetAllSpreadRestController,
    GetSpreadByIdRestController,
    CreateRemittanceExposureRuleRestController,
    UpdateRemittanceExposureRuleRestController,
    GetAllRemittanceExposureRuleRestController,
    GetAllExchangeQuotationRestController,
    GetAllRemittanceOrdersByFilterRestController,
    GetRemittanceOrderByIdRestController,
    CreateRemittanceOrderRestController,
    GetAllRemittanceRestController,
    ManuallyCloseRemittanceRestController,
    GetRemittanceByIdRestController,
  ],
})
export class OtcModule {}
