import { Module } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';
import {
  BcryptModule,
  KafkaModule,
  ValidationModule,
  TranslateModule,
  LoggerModule,
} from '@zro/common';
import {
  GetDepositByIdRestController,
  GetCompanyRestController,
  GetDevolutionsRestController,
  GetDevolutionByIdRestController,
  GetDepositsRestController,
  GetOrderByIdRestController,
  GetOrdersRestController,
  GetOrdersRefundsRestController,
  GetOrderRefundsByIdRestController,
  GetWithdrawalByIdRestController,
  GetWithdrawalsRestController,
  GetRefundByIdRestController,
  GetRefundsRestController,
  CheckWalletsRestController,
  GetDashboardRestController,
  GetTransactionExportsRestController,
  GetSupportsRefundReceiptsBankAccountsRestController,
  GetSupportsWithdrawReceiptsBankAccountsRestController,
  PaymentsGatewayAxiosService,
  GetValidationKycCountRestController,
  GetValidationAdminKycCountRestController,
  GetValidationClientKycCountRestController,
} from '@zro/api-users/infrastructure';
import {
  CheckWalletsServiceKafka,
  GetCompanyServiceKafka,
  GetDashboardServiceKafka,
  GetOrderByIdServiceKafka,
  GetOrdersServiceKafka,
  GetOrdersRefundsServiceKafka,
  GetOrdersRefundsByIdServiceKafka,
  GetRefundByIdServiceKafka,
  GetRefundsServiceKafka,
  GetDepositByIdServiceKafka,
  GetDepositsServiceKafka,
  GetDevolutionByIdServiceKafka,
  GetDevolutionsServiceKafka,
  GetWithdrawalByIdServiceKafka,
  GetWithdrawalsServiceKafka,
  GetSupportsRefundReceiptsBankAccountsServiceKafka,
  GetSupportsWithdrawReceiptsBankAccountsServiceKafka,
  GetValidationKycCountServiceKafka,
  GetValidationAdminKycCountServiceKafka,
  GetValidationClientKycCountServiceKafka,
} from '@zro/payments-gateway/infrastructure';

/**
 * PaymentsGateway endpoint modules.
 */
@Module({
  imports: [
    ConfigModule,
    LoggerModule,
    KafkaModule.forFeature([
      CheckWalletsServiceKafka,
      GetCompanyServiceKafka,
      GetDashboardServiceKafka,
      GetOrderByIdServiceKafka,
      GetOrdersServiceKafka,
      GetOrdersRefundsServiceKafka,
      GetOrdersRefundsByIdServiceKafka,
      GetRefundByIdServiceKafka,
      GetRefundsServiceKafka,
      GetDepositByIdServiceKafka,
      GetDepositsServiceKafka,
      GetDevolutionByIdServiceKafka,
      GetDevolutionsServiceKafka,
      GetWithdrawalByIdServiceKafka,
      GetWithdrawalsServiceKafka,
      GetSupportsRefundReceiptsBankAccountsServiceKafka,
      GetSupportsWithdrawReceiptsBankAccountsServiceKafka,
      GetValidationKycCountServiceKafka,
      GetValidationAdminKycCountServiceKafka,
      GetValidationClientKycCountServiceKafka,
    ]),
    BcryptModule,
    ValidationModule,
    TranslateModule,
  ],
  controllers: [
    GetDepositByIdRestController,
    GetCompanyRestController,
    GetDevolutionsRestController,
    GetDevolutionByIdRestController,
    GetDepositsRestController,
    GetOrderByIdRestController,
    GetOrdersRestController,
    GetOrdersRefundsRestController,
    GetOrderRefundsByIdRestController,
    GetWithdrawalByIdRestController,
    GetWithdrawalsRestController,
    GetRefundByIdRestController,
    GetRefundsRestController,
    CheckWalletsRestController,
    GetDashboardRestController,
    GetTransactionExportsRestController,
    GetSupportsRefundReceiptsBankAccountsRestController,
    GetSupportsWithdrawReceiptsBankAccountsRestController,
    GetValidationKycCountRestController,
    GetValidationAdminKycCountRestController,
    GetValidationClientKycCountRestController,
  ],
  providers: [PaymentsGatewayAxiosService],
})
export class PaymentsGatewayModule {}
