import { Module } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';
import { KafkaModule, TranslateModule } from '@zro/common';
import {
  ApproveOwnershipClaimStartProcessRestController,
  ApprovePortabilityClaimStartProcessRestController,
  VerifyCodePixKeyRestController,
  SendCodePixKeyRestController,
  CancelStartClaimProcessByIdPixKeyRestController,
  CancelStartPortabilityProcessByIdPixKeyRestController,
  CreatePixKeyRestController,
  DeleteByIdPixKeyRestController,
  DismissByIdPixKeyRestController,
  GetAllPixKeyRestController,
  V2GetAllPixKeyByUserRestController,
  GetByIdPixKeyRestController,
  ApprovePortabilityClaimProcessRestController,
  CancelPortabilityClaimProcessRestController,
  CancelCodePixKeyRestController,
  CreateDecodedPixKeyRestController,
  CancelingOwnershipClaimProcessRestController,
  CancelingPortabilityClaimProcessRestController,
} from '@zro/api-users/infrastructure';
import {
  GetAllPixKeyByUserServiceKafka,
  ApproveOwnershipClaimStartProcessServiceKafka,
  ApprovePortabilityClaimProcessServiceKafka,
  ApprovePortabilityClaimStartProcessServiceKafka,
  CancelCodePixKeyServiceKafka,
  CancelPortabilityClaimProcessServiceKafka,
  CancelStartClaimProcessByIdPixKeyServiceKafka,
  CancelStartPortabilityProcessByIdPixKeyServiceKafka,
  CreateDecodedPixKeyServiceKafka,
  CreatePixKeyServiceKafka,
  DeleteByIdPixKeyServiceKafka,
  DismissByIdPixKeyServiceKafka,
  GetAllPixKeyServiceKafka,
  GetPixKeyByIdServiceKafka,
  SendCodePixKeyServiceKafka,
  VerifyCodePixKeyServiceKafka,
  CancelingPortabilityClaimProcessServiceKafka,
  CancelingOwnershipClaimProcessServiceKafka,
} from '@zro/pix-keys/infrastructure';

/**
 * PixKey endpoint modules.
 */
@Module({
  imports: [
    ConfigModule,
    KafkaModule.forFeature([
      GetAllPixKeyByUserServiceKafka,
      ApproveOwnershipClaimStartProcessServiceKafka,
      ApprovePortabilityClaimProcessServiceKafka,
      ApprovePortabilityClaimStartProcessServiceKafka,
      CancelCodePixKeyServiceKafka,
      CancelPortabilityClaimProcessServiceKafka,
      CancelStartClaimProcessByIdPixKeyServiceKafka,
      CancelStartPortabilityProcessByIdPixKeyServiceKafka,
      CreateDecodedPixKeyServiceKafka,
      CreatePixKeyServiceKafka,
      DeleteByIdPixKeyServiceKafka,
      DismissByIdPixKeyServiceKafka,
      GetAllPixKeyServiceKafka,
      GetPixKeyByIdServiceKafka,
      SendCodePixKeyServiceKafka,
      VerifyCodePixKeyServiceKafka,
      CancelingPortabilityClaimProcessServiceKafka,
      CancelingOwnershipClaimProcessServiceKafka,
    ]),
    TranslateModule,
  ],
  controllers: [
    CreateDecodedPixKeyRestController,
    CreatePixKeyRestController,
    GetAllPixKeyRestController,
    V2GetAllPixKeyByUserRestController,
    GetByIdPixKeyRestController,
    DeleteByIdPixKeyRestController,
    DismissByIdPixKeyRestController,
    SendCodePixKeyRestController,
    VerifyCodePixKeyRestController,
    ApprovePortabilityClaimStartProcessRestController,
    CancelStartPortabilityProcessByIdPixKeyRestController,
    CancelingPortabilityClaimProcessRestController,
    ApproveOwnershipClaimStartProcessRestController,
    CancelStartClaimProcessByIdPixKeyRestController,
    CancelingOwnershipClaimProcessRestController,
    ApprovePortabilityClaimProcessRestController,
    CancelPortabilityClaimProcessRestController,
    CancelCodePixKeyRestController,
  ],
})
export class PixKeyModule {}
