global:
  scrape_interval: 15s
  scrape_timeout: 1s
  evaluation_interval: 15s

scrape_configs:
- job_name: dev-push-gateway
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: ['pushgateway:9091']
    labels:
      service: 'prom-pushgateway'

- job_name: 'otel-collector'
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: ['otel-collector:8889']
    labels:
      service: 'prom-otelcollector'