export interface TopazioGatewayConfig {
  APP_ENV: string;
  APP_TOPAZIO_AUTH_CLIENT_ID: string;
  APP_TOPAZIO_AUTH_CLIENT_SECRET: string;
  APP_TOPAZIO_AUTH_BASE_URL: string;
  APP_TOPAZIO_KYC_BASE_URL: string;
  APP_TOPAZIO_TRANSFER_BASE_URL: string;
  APP_TOPAZIO_EXCHANGE_QUOTATION_BASE_URL: string;
  APP_TOPAZIO_EXCHANGE_CONTRACT_BASE_URL: string;
}
