export enum CancelPaymentCodeEnum {
  ALREADY_CANCELLED = 'ALREADY_CANCELLED',
  CANCELLED_BY_USER = 'CANCELLED_BY_USER',
  CANCELLED_BY_SELLER = 'CANCELLED_BY_SELLER',
  ALREADY_DENIED = 'ALREADY_DENIED',
  ALREADY_SETTLED = 'ALREADY_SETTLED',
  ALREADY_REFUNDED = 'ALREADY_REFUNDED',
  SYSTEM_ERROR = 'SYSTEM_ERROR',
}
