export interface MercadoBitcoinGatewayConfig {
  APP_ENV: string;
  APP_MERCADO_BITCOIN_API_TOKEN_ID: string;
  APP_MERCADO_BITCOIN_API_TOKEN_SECRET: string;
  APP_MERCADO_BITCOIN_BASE_URL: string;
  APP_MERCADO_BITCOIN_WEBSOCKET_URL: string;
  APP_MERCADO_BITCOIN_SUBSCRIBE_TYPE: string;
  APP_MERCADO_BITCOIN_ORDERBOOK_DEPTH: number;
  APP_MERCADO_BITCOIN_ACCOUNT_ID: string;
  APP_STREAM_QUOTATIONS_CACHE_DEFAULT_TTL_MS: number;
  APP_MERCADO_BITCOIN_HISTORICAL_PRICE_BASE_URL: string;
}
